trigger:
- main

pool: default
  

variables:
  solution: 'DougsExoticPetStore.sln'
  buildPlatform: 'Any CPU'
  buildConfigurtion: 'Release'

steps:
- task: SonarCloudPrepare@1
  displayName: SonarCloud Prep
  inputs:
    SonarCloud: 'SonarCloudMM'
    organization: '210503-reston-net'
    scannerMode: 'MSBuild'
    projectKey: '210503-Reston-NET_Austin-Douglas-p1'
    projectName: 'Austin-Douglas-p1'
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: $(solution)
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: $(solution)
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: 'Tests/*.csproj'
- task: SonarCloudAnalyze@1
  displayName: Run Code Analysis
- task: SonarCloudPublish@1
  displayName: Publish Code Analysis
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true
    projects: 'StoreUI/*.csproj'
- task: AzureRmWebAppDeployment@4
  displayName: Deploy
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(958dfd28-6f5e-4833-be1f-aa14358bb930)'
    appType: 'webApp'
    WebAppName: 'DougsExoticPetStore'